#!/usr/bin/env node

import { createHash } from 'node:crypto';
import { mkdir, readdir, realpath, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { loadAndValidateChecklist } from './validate.mjs';

const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

async function checklistFiles(root) {
  const files = [];
  async function visit(directory) {
    let entries;
    try {
      entries = await readdir(directory, { withFileTypes: true });
    } catch (error) {
      if (error.code === 'ENOENT' && directory === root) return;
      throw error;
    }
    for (const entry of entries) {
      const path = join(directory, entry.name);
      if (entry.isDirectory()) await visit(path);
      else if (entry.isFile() && entry.name.endsWith('.json')) files.push(path);
    }
  }
  await visit(root);
  return files.sort((left, right) => left.localeCompare(right));
}

function sha256(value) {
  return createHash('sha256').update(value).digest('hex');
}

export async function buildChecklists(repoDir = process.cwd(), outputPath) {
  const canonicalRepo = await realpath(repoDir);
  const root = join(canonicalRepo, 'checklists');
  const files = await checklistFiles(root);
  const checklists = [];
  const failures = [];

  for (const path of files) {
    const source = relative(root, path).split(sep).join('/');
    const identity = source.slice(0, -'.json'.length);
    const segments = identity.split('/');
    if (segments.length < 2 || segments.some((segment) => !SLUG.test(segment))) {
      failures.push(`${source}: path must be <category>/<slug>.json using lowercase slugs`);
      continue;
    }
    const { checklist, errors } = await loadAndValidateChecklist(path);
    if (errors.length > 0) {
      failures.push(...errors.map((error) => `${source}: ${error}`));
      continue;
    }
    const category = segments.slice(0, -1).join('/');
    checklists.push({
      identity,
      category,
      contentHash: `sha256:${sha256(JSON.stringify(checklist))}`,
      checklist,
    });
  }

  if (failures.length > 0) {
    throw new Error(`Checklist build failed:\n${failures.map((failure) => `- ${failure}`).join('\n')}`);
  }

  const payload = {
    generatedAt: new Date().toISOString(),
    repositoryId: `sha256:${sha256(canonicalRepo)}`,
    categories: [...new Set(checklists.map((entry) => entry.category))],
    checklists,
  };
  const serialized = JSON.stringify(payload).replaceAll('<', '\\u003c');
  const target = outputPath ?? resolve(dirname(fileURLToPath(import.meta.url)), '../previewer/data.generated.js');
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, `// Generated by bearings. Do not edit.\nwindow.BEARINGS_CHECKLISTS = ${serialized};\n`);
  return payload;
}

async function main() {
  const repoDir = process.argv[2] ?? process.cwd();
  const outputPath = process.argv[3];
  if (process.argv.length > 4) {
    console.error('Usage: node build.mjs [repository] [output]');
    process.exitCode = 1;
    return;
  }
  try {
    const payload = await buildChecklists(repoDir, outputPath);
    console.log(`Built ${payload.checklists.length} checklist(s).`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main();
